# Generated by Django 4.2.15 on 2024-08-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('description', models.TextField(blank=True, default='', max_length=350, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('booking_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capitalCity', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=350, null=True)),
                ('image', models.ImageField(upload_to='provinces/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('description', models.TextField(blank=True, default='', max_length=350, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('booking_link', models.URLField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.province')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.ImageField(upload_to='hotels/')),
                ('password', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.province')),
            ],
        ),
        migrations.CreateModel(
            name='TourismSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=350, null=True)),
                ('image', models.ImageField(upload_to='tourism_sites/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('booking_link', models.URLField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.province')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('text', models.TextField()),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourguide.hotel')),
                ('rental_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourguide.rentalcar')),
                ('tourism_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourguide.tourismsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('tourism_site', 'Tourism Site'), ('hotel', 'Hotel'), ('rental_car', 'Rental Car')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.user')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.province'),
        ),
    ]
