# Generated by Django 4.2.15 on 2024-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rentalcar',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rentalcar',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tourismsite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tourismsite',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tourismsite',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='image',
            field=models.ImageField(upload_to='car_servicess/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
