# Generated by Django 4.2.16 on 2024-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0002_rename_firstname_user_name_remove_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismsite',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
