# Generated by Django 5.0.2 on 2024-09-15 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0003_tourismsite_address_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MostVisitedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
                ('description', models.TextField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.province')),
            ],
        ),
    ]
