# Generated by Django 5.0.2 on 2024-09-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0004_video_mostvisitedsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rentalcar',
            name='province',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rental_car',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tourism_site',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RentalCar',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
